### ISSUE TITLE
handle case where `standard_name` attribute is not lowercase

### ISSUE THREAD

**Issue by rsignell-usgs** [pyoceans/erddapy#12]
It sucks that we here we find a dataset with the requested `standard_name`, but then when we try to get the variable associated with that `standard_name`, we fail:
![2017-11-12_14-36-01](https://user-images.githubusercontent.com/1872600/32702574-2b3d58c2-c7b7-11e7-9bbd-289ea6bb11bf.png)

The problem is that in this dataset, the `standard_name` is not lower case:  It's `Sea_Water_Pressure` instead of `sea_water_pressure`:

![2017-11-12_14-40-51](https://user-images.githubusercontent.com/1872600/32702598-9afe7ba0-c7b7-11e7-9f3b-83a33eb0786a.png)
so our test against `sea_water_pressure` fails. 

I'm not sure how to best solve this in ERDDAPY.  We could just do `string.lower()` but that would probably cause failures for attributes other than `standard_name`. 

Or @BobSimons, perhaps we could fix this on the ERDDAP end?   
Maybe ERDDAP could make all `standard_name` attributes lower case?

Notebook here:
https://gist.github.com/rsignell-usgs/c6647e8debdce4654a90f8321389bd18

**Comment by ocefpaf** [comment]
We could use .lower but I would argue that a standard_name with upper case letters is wrong and the metadata needs to be corrected.

**Comment by rsignell-usgs** [comment]
But since this is ERDDAP we are talking about, Bob could just lowercase all standard_names on the server side, so we don't have to change all the NetCDF files ever made this way.

**Comment by ocefpaf** [comment]
> But since this is ERDDAP we are talking about, Bob could just lowercase all standard_names on the server side

I am :+1:  to that but unless ERDDAP is the canonical place to access that data warning the data provider would be nice too.

I am against any changes to `erddapy`'s code base to implement that b/c we need to be explicitly about what the user is searching. I'd like to avoid any ambiguity. However, the user can easily provide a smart `lambda` function to circumvent that:

```python
e.get_var_by_attr(
    dataset_id=datasets[0],
    standard_name=lambda v: str(v).lower() == 'sea_water_pressure'
)
```

**Comment by rsignell-usgs** [comment]
I just wanted to report that this worked great:
```
def get_data(dataset, standard_name, kwargs):
    var = e.get_var_by_attr(dataset_id=dataset, 
                    standard_name=lambda v: str(v).lower() == standard_name)[0]
    download_url = e.get_download_url(dataset_id=dataset, 
                                  variables=['time',var], response='csv', **kwargs)
    df = download_csv(download_url)
    return df, var
```
```
kwargs = {'time%3E=': min_time, 'time%3C=': max_time}
df, var = get_data(initial_dataset, initial_standard_name, kwargs)
```
