### ISSUE TITLE
simpler parse_dates?

### ISSUE THREAD

**Issue by rsignell-usgs** [pyoceans/erddapy#16]
@ocefpaf ,  the purpose of parse_dates is to convert to seconds since 1970, right?

Why not just:      `timestamp()` instead of this code:
https://github.com/pyoceans/erddapy/blob/master/erddapy/utilities.py#L24-L34

**Comment by ocefpaf** [comment]
The idea was to support multiple calendars but later I found out that ERDDAP standardizes everything.
That change makes sense to me. Do you want to implement it?

**Comment by rsignell-usgs** [comment]
Sure.

**Comment by ocefpaf** [comment]
Done in #17
