### ISSUE TITLE
Need to quote strings in queries

### ISSUE THREAD

**Issue by rsignell-usgs** [pyoceans/erddapy#18]
We need to quote strings when used in ERDDAP expressions. 

This code:
```python
    kwargs = {
        'minTime<=': stop_time.value,
        'maxTime>=': start_time.value,
        'cdm_data_type=': cdm_data_type
    }

    variables = ['datasetID', 'minLongitude', 'minLatitude']
    url = e.get_download_url(dataset_id='allDatasets', variables=variables, response='csv', **kwargs)
```
produces this URL
https://erddap-uncabled.oceanobservatories.org/uncabled/erddap/tabledap/allDatasets.csv?datasetID,minLongitude,minLatitude&minTime%3C=2018-01-23T12:52:10Z&maxTime%3E=2018-01-16T12:52:10Z&cdm_data_type=TimeSeries

which gives the response:
```
Query error: For constraints of String variables, the right-hand-side value must be surrounded by double quotes. Bad constraint: cdm_data_type=TimeSeries
```

**Comment by ocefpaf** [comment]
I think I have a fix for that already somewhere. Just need time to organize it in a PR here.

**Comment by rsignell-usgs** [comment]
Is this a bit tricky, since time values can be strings, but should not be quoted?

**Comment by rsignell-usgs** [comment]
Actually, I just did some testing, and seems that ERDDAP can handle having quotes around the time strings, so I guess we can quote all strings!

These both work:

https://erddap-uncabled.oceanobservatories.org/uncabled/erddap/tabledap/allDatasets.csv?datasetID,minLongitude,minLatitude&minTime<=2018-01-23T12:52:10Z&maxTime>=2018-01-16T12:52:10Z&cdm_data_type="Point"

https://erddap-uncabled.oceanobservatories.org/uncabled/erddap/tabledap/allDatasets.csv?datasetID,minLongitude,minLatitude&minTime<="2018-01-23T12:52:10Z"&maxTime>="2018-01-16T12:52:10Z"&cdm_data_type="Point"

https://erddap-uncabled.oceanobservatories.org/uncabled/erddap/tabledap/allDatasets.csv?datasetID,minLongitude,minLatitude&minTime%3C=%222018-01-23T12:52:10Z%22&maxTime%3E=%222018-01-16T12:52:10Z%22&cdm_data_type=Point

**Comment by ocefpaf** [comment]
@rsignell-usgs we cannot quote longitude and latitude like with times. Also, `erddapy` can take `datetime` objects too, not only strings, so we need to be careful with that. I believe I got a pattern that will solve this. See http://nbviewer.jupyter.org/gist/ocefpaf/6c7f7f6e151e550a085796c0069bfe00 for an example and https://github.com/pyoceans/erddapy/pull/19 for the code.
