### ISSUE TITLE
ImportError: No module named tslibs.parsing

### ISSUE THREAD

**Issue by BrianOBlanton** [pyoceans/erddapy#34]
Hi,  when importing erddapy, I get this: 

**from erddapy import ERDDAP**
...
...
**ImportError: No module named tslibs.parsing**

Is this a pandas problem?    Here's the complete traceback: 

```python 
ImportErrorTraceback (most recent call last)
<ipython-input-3-20c6c8f35979> in <module>()
----> 1 from erddapy import ERDDAP

/home/bblanton/.local/lib/python2.7/site-packages/erddapy/__init__.py in <module>()
      1 from __future__ import (absolute_import, division, print_function)
      2 
----> 3 from erddapy.erddapy import ERDDAP, servers
      4 
      5 __all__ = [

/home/bblanton/.local/lib/python2.7/site-packages/erddapy/erddapy.py in <module>()
      8 from __future__ import (absolute_import, division, print_function)
      9 
---> 10 from erddapy.url_builder import (
     11     download_url,
     12     info_url,

/home/bblanton/.local/lib/python2.7/site-packages/erddapy/url_builder.py in <module>()
     18     from urllib import quote_plus
     19 
---> 20 from erddapy.utilities import (_check_url_response, parse_dates, quote_string_constraints)
     21 
     22 

/home/bblanton/.local/lib/python2.7/site-packages/erddapy/utilities.py in <module>()
     10 from collections import namedtuple
     11 
---> 12 from pandas._libs.tslibs.parsing import parse_time_string
     13 
     14 import pytz

ImportError: No module named tslibs.parsing
```

**Comment by ocefpaf** [comment]
Can you check the version of pandas that you have installed there?
You can copy and paste this in the command line:

```shell
python -c 'import pandas; print(pandas.__version__)'
```

**Comment by BrianOBlanton** [comment]
0.20.3

**Comment by ocefpaf** [comment]
Can you update to `0.22.0`? I'll try to add some backwards compatibility, I never realized that `parse_time_string` was so new.

**Comment by BrianOBlanton** [comment]
Yes, I will., and let you know.

**Comment by BrianOBlanton** [comment]
that worked! thanks.  I'll start getting data...

**Comment by ocefpaf** [comment]
Awesome! I'll leave this open to remind me to add support for older pandas.

**Comment by BrianOBlanton** [comment]
OK. Thanks again.


Cheers,

[/Users/bblanton/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_513915552]

Brian O. Blanton, Ph.D.
Director of Earth Data Sciences
Oceanographer
Renaissance Computing Institute
University of North Carolina at Chapel Hill
100 Europa Drive
Suite 540 Chapel Hill, NC, 27517

Brian_Blanton@Renci.Org<mailto:Brian_Blanton@Renci.Org>
919-445-9620 (O)
